version: '3'
services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile.postgresql
    environment:
      POSTGRES_USER: scrumex
      POSTGRES_PASSWORD: password
  web:
    build: ./
    command: sh -c "yarn install && mix deps.get && mix phoenix.server"
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    - /usr/src/app/_build
    ports:
    - '4000:4000'
    links:
    - db:db
    depends_on:
    - db
